# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e6173dda0c97f092ef05bb8c0be84a2f1e661460fc54e18f1306c89137e755373a5b722adfefd8bc461a3b08bdfa8da1449e00e6d164134714469de9eae4803

test:
  secret_key_base: c434d97180c39d777d11df37519eb4954240416f5e77b8870f03297404640c457d922fd895bb2828b8d19c360a85c8784d20100ac86d9f2cde8bcadaf4af0044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
